                                                 SECTION A


A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasonsNumPy arrays are generally preferred over Python lists for numerical computation in AI/ML because:

1. Faster computation: NumPy uses optimized, low-level C implementations and supports vectorized operations, making numerical calculations much faster than Python loops over lists.

2. Memory efficient: NumPy arrays store elements of the same data type in a compact, contiguous block of memory, using less memory than Python lists.

Example:`arr1 + arr2` performs element-wise addition directly in NumPy, without needing an explicit loop.


A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? 

Vectorization is the process of performing operations on an entire NumPy array at once instead of using an explicit Python loop to process each element individually.

Why it matters for large datasets:

Faster execution: NumPy performs operations using optimized low-level code, which is much faster than Python loops.

Better efficiency: It reduces Python-level overhead and can process large amounts of data efficiently.


A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

For compatible 2D NumPy arrays A and B:

A * B → Performs element-wise multiplication, multiplying corresponding elements of A and B.
Neural-network situation: Applying an element-wise mask or gating operation to neural-network activations.

A @ B → Performs matrix multiplication, where rows of A are multiplied with columns of B.
Neural-network situation: Computing the weighted sum in a dense (fully connected) layer, such as X @ W.


A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.
 
 Broadcasting in NumPy is a mechanism that allows arrays with different shapes to be used together in element-wise operations without explicitly reshaping them.

General rule: Two dimensions are compatible when:

They are equal, or
One of them is 1.

The comparison starts from the last (rightmost) dimension and moves toward the left.

Example:
A (3, 4) array and a (4,) array can be added because 4 matches 4

A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why? 

flatten() converts a multi-dimensional array into a 1D array and always creates a copy of the data.

ravel() converts an array into a 1D array and usually returns a view of the original data when possible.

For a memory-constrained application: I would prefer ravel() because it usually does not create an additional copy, so it uses less memory when processing large images.

A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example. [2 marks]
In a 2D NumPy array:

axis=0 → performs the operation column-wise (down the rows).axis=0 means NumPy performs the operation down the rows, so it combines values in each column.

axis=1 → performs the operation row-wise (across the columns).axis=1 means NumPy performs the operation across the columns, so it combines values in each row.

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))  # [5 7 9]
print(np.sum(arr, axis=1))  # [ 6 15]

[5 7 9]
[ 6 15]


A7.Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization. [2 marks]

It is important to normalize or standardize numerical features because features may have different scales. Without scaling, features with larger values can dominate the model and affect its performance.

Normalization: Scales values to a fixed range, usually 0 to 1.

Example: Min-Max Scaling.

Standardization: Transforms values so they have a mean of 0 and standard deviation of 1.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? [2 marks]

np.nanmean() exist to calculate the mean while ignoring NaN (missing) values.

np.mean(): If the array contains NaN, the result is usually NaN.

np.nanmean(): Ignores the NaN values and calculates the mean using only the available numerical values.

A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128. [2 marks]

In Machine Learning, data is generally represented in the form (samples, features), where samples represent the number of data instances and features represent the information associated with each sample.For a batch of RGB images, each image is represented using height, width, and 3 color channels (Red, Green, Blue). Therefore, for 64 RGB images, each of size 128 × 128, the shape is:(64, 128, 128, 3)

A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed). 

Reproducibility is important in model development because it ensures that the same experiment produces the same results when repeated. This makes it easier to compare models, identify errors, and verify the results.

In NumPy, a random seed can be fixed using np.random.default_rng(seed). It makes the random numbers generated during an experiment consistent each time the program is executed.

rng = np.random.default_rng(42)

                                              Section B – Predict the Output


B1. Predict the exact output and/or resulting shape. Justify in one sentence. [2 marks]


a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

Broadcasting expands (3,) and (3,1) to (3,3) before addition.

Output:(3, 3)

In [ ]:

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)


(3, 3)


B2. Predict the output and/or shape. [2 marks]
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

First x becomes:
 [[1 2 3]
 [4 5 6]]
 
 : selects all rows and 1 selects the second column
 
 Output:[2 5]

In [5]:
x = np.arange(1, 7).reshape(2, 3)

print(x[:, 1])

[2 5]


B3. Predict the output and/or shape. [2 marks]
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

arr % 10 == 0 checks which elements are exactly divisible by 10. Therefore, 10 and 20 are selected.

Output:[10 20]

In [7]:
arr = np.array([5, 10, 15, 20, 25])

print(arr[arr % 10 == 0])

[10 20]


B4. Predict the output and/or shape. [2 marks]

m = np.array([[1, 2], [3, 4]])

print(m.T @ m)

m.T makes Transpose that means rows will be converted into columns and columns into rows

m.T@m makes the matrix multiplication 

@ performs matrix multiplication, so m.T (2,2) multiplied by m (2,2) produces a (2,2) matrix.

Output:[[10 14]
 [14 20]]

In [8]:
m = np.array([[1, 2],
              [3, 4]])

print(m.T @ m)

[[10 14]
 [14 20]]


B5. Predict the output and/or shape. [2 marks]

data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

np.mean(data) → returns nan because the array contains a NaN value.

np.nanmean(data) → ignores NaN and calculates the mean of 1, 2, 4.

Output:nan 2.3333333333333335

In [9]:
data = np.array([1, 2, np.nan, 4])

print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


B6. Predict the output and/or shape. [2 marks]

x = np.array([10, 20, 30])

y = np.where(x > 15, 1, 0)

print(y)

np.where(condition, 1, 0) returns 1 when the condition is true and 0 when it is false.

Output:[0 1 1]

In [10]:
x = np.array([10, 20, 30])

y = np.where(x > 15, 1, 0)

print(y)

[0 1 1]



B7. Predict the output and/or shape. [2 marks]

a = np.zeros((3, 4))

print(a.ndim, a.size)

Output:2,12


In [11]:
a = np.zeros((3, 4))

print(a.ndim, a.size)

2 12


B8. Predict the output and/or shape. [2 marks]

arr = np.arange(1, 13).reshape(3, 4)

print(arr[::-1, ::-1])

[::-1, ::-1] reverses both the rows and columns.

Output:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

In [12]:
arr = np.arange(1, 13).reshape(3, 4)

print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


                                                           Section C – Coding / Implementation
 

C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). [5 marks]

np.where() can be used to assign 'P' (Pass) when the exam score is greater than or equal to 40, and 'F' (Fail) when the score is less than 40.

The condition scores >= 40 is checked for every element. 

If the condition is True, np.where() returns 'P'; otherwise, it returns 'F'.

In [15]:
scores=np.array([35,40,50,67,89,90])
result=np.where(scores>=40,'P','F')
print(result)

['F' 'P' 'P' 'P' 'P' 'P']


C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. [5 marks]

Z-score standardization converts the values of an array so that they have a mean of 0 and a standard deviation of 1

The function uses only NumPy operations and returns the z-score standardized array

np.mean(x) calculates the mean.

np.std(x) calculates the standard deviation.

(x - mean) / std calculates the z-score for each value.

The function returns the standardized NumPy array.


In [12]:
def standardize(x):
    return(x-np.mean(x))/np.std(x)
x=np.array([10,20,30,40,50])
print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape. [5 marks]

When two 2D NumPy arrays represent separate batches with the same number of features, they can be combined row-wise using np.vstack(). This adds the samples of the second batch below the samples of the first batch.

np.vstack() combines the arrays vertically (row-wise). Since each batch has 3 features, the resulting array has 4 samples and 3 features, giving the shape (4, 3).

In [18]:
import numpy as np

batch1 = np.array([[1, 2, 3], [4, 5, 6]])

batch2 = np.array([[7, 8,9],[10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression. [5 marks]

axis=0 calculates the mean and standard deviation for each of the 5 columns.
X - mean uses broadcasting to subtract each column's mean.
Dividing by std standardizes each feature.
The resulting matrix retains the shape (100, 5).


In [20]:
import numpy as np

# Create X with 100 samples and 5 features
X = np.random.rand(100, 5)

# Calculate column-wise mean and standard deviation
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

# Standardize the matrix
X_standardized = (X - mean) / std

print(X_standardized.shape)

(100, 5)


C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. [5 marks]

X @ w + b performs matrix multiplication between the features and weights and then adds the bias. MSE is calculated as the average of the squared differences between y_true and y_pred.

In [15]:
import numpy as np

# Feature matrix
X = np.array([[1, 2], [3,4],[5,6]])

# Weight vector and bias
w = np.array([2, 1])
b = 1

# Prediction
y_pred = X @ w + b

# Actual values
y_true = np.array([6,12,16])

# Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 5 11 17]
MSE: 1.0


C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. [5 marks]

np.random.default_rng() is used to generate random numbers in NumPy.

A fixed seed is used to make the random numbers reproducible. This means that whenever we use the same seed, NumPy generates the same random values.

Here:

42 → fixed seed.
size=(10,3) → generates 10 samples and 3 features.
X.shape → gives (10,3).
Using another generator with the same seed produces identical results.


In [22]:
import numpy as np

# Create random generator with a fixed seed
rng1 = np.random.default_rng(42)

# Generate 10 samples and 3 features
X1 = rng1.normal(size=(10, 3))

print("Shape:", X1.shape)

# Create another generator with the same seed
rng2 = np.random.default_rng(42)

X2 = rng2.normal(size=(10, 3))

# Check whether both results are identical
print("Identical results:", np.array_equal(X1, X2))

Shape: (10, 3)
Identical results: True


C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization. [5 marks]

A grayscale image is represented as a 2D NumPy array, where each value represents a pixel intensity.

Normally, pixel values range from 0 to 255.

Min-Max normalization converts these values to the range 0 to 1.


In [23]:
import numpy as np

image = np.array([[0, 128], [200, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.50196078]
 [0.78431373 1.        ]]


C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why. [5 marks]

The dimensions represent:

4 → number of images
28 → height
28 → width
3 → RGB channels

We need to calculate one average value for each image.
axis=1 → average across height.
axis=2 → average across width.
axis=3 → average across RGB channels.
axis=0 is not included because it represents the 4 separate images.

Therefore, the result contains 4 values, one average pixel value for each image.


In [11]:
images=np.random.default_rng(42).random((4,28,28,3))
average_pixels=np.mean(images,axis=(1,2,3))
print(average_pixels)
print(average_pixels.shape)

[0.49879444 0.49546077 0.48993754 0.50644914]
(4,)


                                                          SECTION-D

D1. Data Preprocessing Pipeline [8 marks]

You are given a raw 1D or 2D NumPy array containing NaN values.
Describe, step by step, the NumPy operations you would apply to:
(a) detect missing values,
(b) handle them appropriately and justify your strategy, and
(c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.


Explanation

Data preprocessing is the process of cleaning and transforming raw data before giving it to a machine learning model.

The pipeline can be divided into three main steps:

(a) Detect missing values

NumPy represents missing numerical values using NaN (Not a Number).

We can detect NaN values using:

np.isnan(data)

It returns True wherever a missing value is present.

To check whether any NaN exists, we can use:

np.isnan(data).any()

(b) Handle missing values

Missing values should be handled before training the model because many ML algorithms cannot work directly with NaN values.

For numerical data, a common strategy is to replace NaN with the mean of the available values.

np.nanmean(data)

nanmean() calculates the mean while ignoring NaN values.

Then we can replace NaN values using:

data[np.isnan(data)] = mean

Why mean imputation?

Mean imputation is simple and suitable when the missing values are relatively few and the numerical data does not contain extreme outliers.

(c) Normalize or standardize the clean data

After handling missing values, the data can be standardized so that features have a comparable scale.

Standardization uses:

 Z =X-mean/Standard deviation



After standardization, the data approximately has mean 0 and standard deviation 1.

For a 2D array, we use axis=0 so that each column/feature is standardized separately

In [ ]:
import numpy as np

# Step 1: Create sample data containing NaN
data = np.array([[10, 20], [15, np.nan],[30, 40],[25, 50]], dtype=float)

print("Original data:")
print(data)

# Step 2: Detect missing values
missing = np.isnan(data)

print("\nMissing value locations:")
print(missing)

print("\nAny missing values:", np.isnan(data).any())

# Step 3: Handle missing values using column-wise mean
column_mean = np.nanmean(data, axis=0)

data[np.isnan(data)] = np.take(
    column_mean,
    np.where(np.isnan(data))[1]
)

print("\nData after handling NaN:")
print(data)

# Step 4: Standardize the clean data
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

standardized = (data - mean) / std

print("\nStandardized data:")
print(standardized)


Original data:
[[10. 20.]
 [15. nan]
 [30. 40.]
 [25. 50.]]

Missing value locations:
[[False False]
 [False  True]
 [False False]
 [False False]]

Any missing values: True

Data after handling NaN:
[[10.         20.        ]
 [15.         36.66666667]
 [30.         40.        ]
 [25.         50.        ]]

Standardized data:
[[-1.26491106 -1.5430335 ]
 [-0.63245553  0.        ]
 [ 1.26491106  0.3086067 ]
 [ 0.63245553  1.2344268 ]]


D2. Image Batch Understanding [8 marks]

Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

Compute the average image of the batch, meaning the element-wise mean across all 16 images.

State the shape of your result and explain why.


EXPLANATION:

A single RGB image of size 64 × 64 has the shape (64, 64, 3), where 3 represents the Red, Green, and Blue color channels. A batch of 16 RGB images has the shape (16, 64, 64, 3), where 16 represents the number of images. In the code, np.random.default_rng(42) is used to generate random values, and rng.integers(0, 256, size=(16, 64, 64, 3)) creates 16 images with pixel values between 0 and 255. Then, np.mean(images, axis=0) calculates the average image by taking the mean of the corresponding pixels across all 16 images. Since axis=0 represents the image dimension, it is removed after averaging, while the height, width, and RGB channels remain. Therefore, the resulting average image has the shape (64, 64, 3)


In [16]:
rng = np.random.default_rng(42)
images = rng.integers(0, 256, size=(16, 64, 64, 3))
print("Batch shape:", images.shape)
average_image = np.mean(images, axis=0)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)




D3. Debug the Model Code [8 marks]
The following code contains more than one bug:

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)

Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

There are two main bugs in the given code.

Bug 1: Weight vector has the wrong shape

The input matrix X has shape (3, 2), meaning there are:

3 samples
2 features per sample

Therefore, the weight vector must contain 2 weights, one for each feature.

But the given:

w = np.array([0.5, 1.0, 0.2])

has shape (3,).

The matrix multiplication:

X @ w

requires the number of columns in X to match the size of w.

Here:

X → (3, 2)
w → (3,)

The dimensions 2 and 3 do not match, so matrix multiplication produces a shape error.

It should be:

w = np.array([0.5, 1.0])

Now:

X → (3, 2)
w → (2,)
X @ w → (3,)

Bug 2: Incorrect operator precedence in MSE

The given expression is:

mse = np.mean(y_true - y_pred ** 2)

The problem is that Python evaluates the exponentiation ** before subtraction.

So it is interpreted as:

mse = np.mean(y_true - (y_pred ** 2))

But the Mean Squared Error formula is:

MSE = mean((y_true - y_pred)²)

Therefore, the difference must be calculated first, and then squared:

mse = np.mean((y_true - y_pred) ** 2)


In [8]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)

w = np.array([0.5, 1.0])  # shape (2,)

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("X shape:", X.shape)
print("w shape:", w.shape)
print("y_pred:", y_pred)
print("MSE:", mse)

X shape: (3, 2)
w shape: (2,)
y_pred: [4.5 6.  7.5]
MSE: 244.16666666666666


E1. Per-Column Min–Max Normalization [5 marks]

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.


Min-Max normalization scales each feature independently to the range 0 to 1.

The formula is:

X_{norm} = (X-Xmin)/(Xmax-Xmin)

For per-column normalization, we calculate the minimum and maximum separately for each column using axis=0.


In [9]:
import numpy as np

# 2D feature matrix
X = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000],
    [40, 400, 4000]
])

# Find minimum and maximum of each column
X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)

# Per-column Min-Max normalization
X_norm = (X - X_min) / (X_max - X_min)

print("Original matrix:")
print(X)

print("\nNormalized matrix:")
print(X_norm)

Original matrix:
[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

Normalized matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


E2. Three-Level Score Classification [5 marks]


Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
Hint: You may need to nest or combine np.where() calls.

The first np.where() checks whether the score is less than 40.

If score < 40 → "Fail"
Otherwise, the second np.where() checks whether the score is less than or equal to 70.
40 ≤ score ≤ 70 → "Average"
score > 70 → "Excellent"

In [10]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
